[package]
name = "rateless-tables"
version = "0.2.0"
edition = "2024"

[dependencies]
libm = "0.2.15"

[dependencies.serde]
version = "1.0.228"
default-features = false
features = ["alloc", "derive"]
